// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-aj7GrarBCafeh3zVVo4YKHcHGt5E22Y',
    appId: '1:206260445368:web:26c041ff4b22e017c8544d',
    messagingSenderId: '206260445368',
    projectId: 'my-expense-41f0f',
    authDomain: 'my-expense-41f0f.firebaseapp.com',
    storageBucket: 'my-expense-41f0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBG5RlAQPAVwc03fO8J3uDaUv53XI_NYg',
    appId: '1:206260445368:android:56baa38075f23f80c8544d',
    messagingSenderId: '206260445368',
    projectId: 'my-expense-41f0f',
    storageBucket: 'my-expense-41f0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3bm7duzK9aICwnVZ58ATVzxCVNVR0Sls',
    appId: '1:206260445368:ios:8d30b4421df59686c8544d',
    messagingSenderId: '206260445368',
    projectId: 'my-expense-41f0f',
    storageBucket: 'my-expense-41f0f.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3bm7duzK9aICwnVZ58ATVzxCVNVR0Sls',
    appId: '1:206260445368:ios:8d30b4421df59686c8544d',
    messagingSenderId: '206260445368',
    projectId: 'my-expense-41f0f',
    storageBucket: 'my-expense-41f0f.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-cBMHOqRt9Pbjjz9HXk3SZa7t9K5Jxns',
    appId: '1:206260445368:web:3d068db61494363ac8544d',
    messagingSenderId: '206260445368',
    projectId: 'my-expense-41f0f',
    authDomain: 'my-expense-41f0f.firebaseapp.com',
    storageBucket: 'my-expense-41f0f.firebasestorage.app',
  );

}